// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndmuamcrsozbhavnohle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kbXVhbWNyc296Ymhhdm5vaGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODI0MTAsImV4cCI6MjA2NzU1ODQxMH0.hz7EM-eXAFwoMXd9v07APcUlc2Ml1C4cIreSy_8ENh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});